// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      categories: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          image: string | null
          product_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string | null
          image?: string | null
          product_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string | null
          image?: string | null
          product_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          name: string
          part_number: string
          oem_number: string | null
          category_id: string | null
          brand: string
          price: number
          description: string | null
          in_stock: boolean
          featured: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          part_number: string
          oem_number?: string | null
          category_id?: string | null
          brand: string
          price: number
          description?: string | null
          in_stock?: boolean
          featured?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          part_number?: string
          oem_number?: string | null
          category_id?: string | null
          brand?: string
          price?: number
          description?: string | null
          in_stock?: boolean
          featured?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      product_images: {
        Row: {
          id: string
          product_id: string
          url: string
          alt_text: string | null
          display_order: number
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          url: string
          alt_text?: string | null
          display_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          url?: string
          alt_text?: string | null
          display_order?: number
          created_at?: string
        }
      }
      product_specifications: {
        Row: {
          id: string
          product_id: string
          spec_key: string
          spec_value: string
          display_order: number
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          spec_key: string
          spec_value: string
          display_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          spec_key?: string
          spec_value?: string
          display_order?: number
          created_at?: string
        }
      }
      product_compatibility: {
        Row: {
          id: string
          product_id: string
          make: string
          model: string
          year_start: number
          year_end: number
          engine_type: string | null
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          make: string
          model: string
          year_start: number
          year_end: number
          engine_type?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          make?: string
          model?: string
          year_start?: number
          year_end?: number
          engine_type?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

